[package]
name = "buo_py_bindings"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pyo3/extension-module"]

[dependencies]
pyo3 = "0.14.0"
buo = { path = "../bin" }
